#!/usr/bin/env bash
# From the Mac: inject F2 (wrong model-version artifact) on RunPod.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
if [[ -f "$ROOT/.env" ]]; then set -a; source "$ROOT/.env"; set +a; fi
export SFB_RUNPOD_SSH="${SFB_RUNPOD_SSH:-g0uutfrnf83h9v-64410f64@ssh.runpod.io}"
export SFB_RUNPOD_KEY="${SFB_RUNPOD_KEY:-$HOME/.ssh/sfb_runpod}"
export SFB_F2_ACTUAL_MODEL="${SFB_F2_ACTUAL_MODEL:-Qwen/Qwen2-7B-Instruct}"
export SFB_F2_REVISION="${SFB_F2_REVISION:-f2826a00ceef68f0f2b946d945ecc0477ce4450c}"
export SFB_F2_EXPECTED_MODEL="${SFB_F2_EXPECTED_MODEL:-Qwen/Qwen2.5-7B-Instruct}"
export SFB_F2_SERVED_MODEL_NAME="${SFB_F2_SERVED_MODEL_NAME:-Qwen/Qwen2.5-7B-Instruct}"
export SFB_HEALTHY_REVISION="${SFB_HEALTHY_REVISION:-a09a35458c702b33eeacc393d103063234e8bc28}"
export SFB_F2_TOKENIZER="${SFB_F2_TOKENIZER:-Qwen/Qwen2.5-7B-Instruct}"
export SFB_F2_TOKENIZER_REVISION="${SFB_F2_TOKENIZER_REVISION:-$SFB_HEALTHY_REVISION}"
PUBKEY="$(cat "${SFB_RUNPOD_KEY}.pub")"
REMOTE="$ROOT/scripts/gpu/remote_bootstrap_f2.sh"
TCP_HOST="${SFB_RUNPOD_TCP_HOST:-}"
TCP_PORT="${SFB_RUNPOD_TCP_PORT:-22}"
POD_WORKDIR="${SFB_POD_WORKDIR:-/workspace/semafailbench}"
if [[ -n "$TCP_HOST" ]]; then
  scp -o BatchMode=yes -o ConnectTimeout=20 -i "$SFB_RUNPOD_KEY" -P "$TCP_PORT" \
    "$ROOT/scripts/serving_artifact_probe.py" "root@${TCP_HOST}:${POD_WORKDIR}/serving_artifact_probe.py"
fi
echo "Injecting isolated F2 (wrong weights, frozen healthy tokenizer) via PTY SSH ($SFB_RUNPOD_SSH)"
echo "  expected=$SFB_F2_EXPECTED_MODEL"
echo "  actual=$SFB_F2_ACTUAL_MODEL revision=$SFB_F2_REVISION"
echo "  served_model_name=$SFB_F2_SERVED_MODEL_NAME"
{
  printf 'export SFB_PUBKEY=%q\n' "$PUBKEY"
  printf 'export SFB_F2_ACTUAL_MODEL=%q\n' "$SFB_F2_ACTUAL_MODEL"
  printf 'export SFB_F2_REVISION=%q\n' "$SFB_F2_REVISION"
  printf 'export SFB_F2_EXPECTED_MODEL=%q\n' "$SFB_F2_EXPECTED_MODEL"
  printf 'export SFB_F2_SERVED_MODEL_NAME=%q\n' "$SFB_F2_SERVED_MODEL_NAME"
  printf 'export SFB_HEALTHY_REVISION=%q\n' "$SFB_HEALTHY_REVISION"
  printf 'export SFB_F2_TOKENIZER=%q\n' "$SFB_F2_TOKENIZER"
  printf 'export SFB_F2_TOKENIZER_REVISION=%q\n' "$SFB_F2_TOKENIZER_REVISION"
  printf 'export HEALTHY_REV=%q\n' "$SFB_HEALTHY_REVISION"
  printf 'export TOKENIZER_REPO=%q\n' "$SFB_F2_TOKENIZER"
  printf 'export TOKENIZER_REV=%q\n' "$SFB_F2_TOKENIZER_REVISION"
  printf 'export SFB_PORT=%q\n' "${SFB_PORT:-8000}"
  printf 'export SFB_HEALTHY_GPU=%q\n' "${SFB_HEALTHY_GPU:-0}"
  printf 'export SFB_POD_WORKDIR=%q\n' "${SFB_POD_WORKDIR:-/workspace/semafailbench}"
  printf 'export ACTUAL_MODEL=%q\n' "$SFB_F2_ACTUAL_MODEL"
  printf 'export REV=%q\n' "$SFB_F2_REVISION"
  printf 'export EXPECTED_MODEL=%q\n' "$SFB_F2_EXPECTED_MODEL"
  printf 'export SERVED_NAME=%q\n' "$SFB_F2_SERVED_MODEL_NAME"
  printf 'export HEALTHY_REV=%q\n' "$SFB_HEALTHY_REVISION"
  cat "$REMOTE"
} | python3 "$ROOT/scripts/gpu/ssh_run.py" --timeout "${SFB_BOOTSTRAP_TIMEOUT:-2400}"
